#!/bin/bash

echo "🚀 Guide de déploiement GreenCare"
echo ""
echo "=================================="
echo "Option 1 : Render.com (RECOMMANDÉ)"
echo "=================================="
echo ""
echo "1. Créer un compte sur https://render.com"
echo "2. Connecter votre repository GitHub"
echo "3. Créer un nouveau 'Web Service'"
echo "4. Configuration :"
echo "   • Name: greencare-api"
echo "   • Environment: Python 3"
echo "   • Build Command: pip install -r backend/requirements.txt"
echo "   • Start Command: uvicorn backend.main:app --host 0.0.0.0 --port \$PORT"
echo "   • Free plan: Gratuit"
echo ""
echo "5. Une fois déployé, vous aurez une URL type:"
echo "   https://greencare-api.onrender.com"
echo ""
echo "=================================="
echo "Option 2 : Railway.app"
echo "=================================="
echo ""
echo "1. Créer un compte sur https://railway.app"
echo "2. New Project → Deploy from GitHub"
echo "3. Sélectionner le repository greencare"
echo "4. Railway détecte automatiquement FastAPI"
echo "5. Variables d'environnement (optionnel):"
echo "   • PORT=8000"
echo ""
echo "=================================="
echo "Option 3 : Netlify (Frontend uniquement)"
echo "=================================="
echo ""
echo "Pour déployer le FRONTEND sur Netlify :"
echo ""
echo "# Installer Netlify CLI"
echo "npm install -g netlify-cli"
echo ""
echo "# Se connecter"
echo "netlify login"
echo ""
echo "# Déployer"
echo "cd frontend"
echo "netlify deploy --prod"
echo ""
echo "=================================="
echo "Option 4 : Tout-en-un avec Render"
echo "=================================="
echo ""
echo "Render peut héberger FRONTEND + BACKEND ensemble :"
echo ""
echo "1. Backend → Web Service (comme ci-dessus)"
echo "2. Frontend → Static Site"
echo "   • Publish directory: frontend"
echo "   • Build command: echo 'No build'"
echo ""
echo "=================================="
echo "📝 IMPORTANT APRÈS DÉPLOIEMENT"
echo "=================================="
echo ""
echo "Mettre à jour l'API_URL dans frontend/script.js et frontend/news.js :"
echo ""
echo "const API_URL = 'https://votre-backend-url.com/api';"
echo ""
echo "=================================="
echo ""
echo "✅ Recommandation : Render.com pour tout héberger gratuitement"
echo ""
